---
title: "Media & Dissemination"
pagetitle: "Media & Dissemination – Jakob Kasper"
---

# Media & dissemination

Op-eds, blog posts, and reports targeted at non-academic audiences. 

## 2026

::: {.pubs}
- van de Wetering, J., Bakker, B. N., van den Bos, W., te Brinke, L., Green, K., van de Groep, S., **Kasper, J.**, Ma, I., Nabben, F., Schumacher, G., Sweijen, S., Toenders, Y., & Crone, E. (2026, March). *Jongerenperspectief op polarisatie. Van verdeeldheid naar verbinding.* [Report](https://heyzine.com/flip-book/c0df86f13e.html){.pub-link}

- **Kasper, J.** (2026, January). *Politics doesn't define how most people see themselves.* The Inquisitive Mind. [Read](https://www.in-mind.org/blog/post/politics-doesnt-define-how-most-people-see-themselves){.pub-link}

- Bakker, B. N., & **Kasper, J.** (2026, January). *Stop formatting before the desk reject: A proposal for staged submissions.* Blog of Trial and Error. [Read](https://doi.org/10.36850/0fe2a79d-7165){.pub-link}
:::

## 2025

::: {.pubs}
- Bakker, B. N., **Kasper, J.**, & Schumacher, G. (2025, July). *Vanaf 16 jaar stemmen? De jongere is er klaar voor.* Algemeen Dagblad. [Read](https://www.ad.nl/opinie/opinie-vanaf-16-jaar-stemmen-de-jongere-is-er-klaar-voor~ab2d4131/){.pub-link}

- **Kasper, J.**, & Gilovich, T. (2025, June). *Why do hostile posts go viral when most people prefer more positive communication?* SPSP Character & Context Blog. [Read](https://spsp.org/news/character-and-context-blog/kasper-gilovich-hostile-social-media-goes-viral-people-prefer-positive-communication){.pub-link}
:::

## 2024

::: {.pubs}
- Schumacher, G., Bakker, B. N., **Kasper, J.**, & Zaslove, M. (2024, December). *Alarmisme over antidemocratische jongeren is misplaatst.* StukRoodVlees. [Read](https://stukroodvlees.nl/alarmisme-over-antidemocratische-jongeren-is-misplaatst/){.pub-link}
:::

## 2023

::: {.pubs}
- SYNC Lab & Hot Politics Lab (2023, December). *Fact sheet: Hoe denken jongeren over politiek?* [Fact sheet](https://www.linkedin.com/posts/lysanne-te-brinke-12523164_fact-sheet-jongeren-politiek-activity-7123239380172853248-PLpE/){.pub-link}
:::
